version: '3.8'

# #networks:
# networks:
#   web:
#     external: true
#   internal:
#     external: false


# Services
services:

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./.docker/nginx
    ports:
      - 80:80

  api:
    build:
      dockerfile: Dockerfile
      context: ./Server
    ports:
      - 3001:80                                   
    volumes:
      - /app/node_modules
      - ./Server:/app
    # labels:
    #   - traefik.http.routers.apiraul.rule=Host(`api.raul.labfp.es`)
    #   - traefik.http.routers.apiraul.tls=true
    #   - traefik.http.routers.apiraul.tls.certresolver=lets-encrypt
    #   - traefik.port=3001'
    # networks:
    #   - internal
    #   - web
    depends_on:
      - mysql

  client:
    build:
      dockerfile: Dockerfile
      context: ./Client
    ports:
      - 3000:80
    volumes:
      - /app/node_modules
      - ./Client:/app
    # labels:
    #   - traefik.http.routers.raul.rule=Host(`raul.labfp.es`)
    #   - traefik.http.routers.raul.tls=true
    #   - traefik.http.routers.raul.tls.certresolver=lets-encrypt
    #   - traefik.port=3000
    # networks:
    #   - internal
    #   - web

  # MySQL Service
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: mobee
      MYSQL_USER: root
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    # networks:
    #   - internal
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10


# PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    # labels:
    #   - traefik.http.routers.dbraul.rule=Host(`db.raul.labfp.es`)
    #   - traefik.http.routers.dbraul.tls=true
    #   - traefik.http.routers.dbraul.tls.certresolver=lets-encrypt
    #   - traefik.port=8080
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    # networks:
    #   - internal
    #   - web
    depends_on:
      - mysql

# Volumes
volumes:
  mysqldata: